import commerceImage from '../assets/project-commerce.png';
import financeImage from '../assets/project-finance.png';
import flowboardImage from '../assets/project-flowboard.png';
import learningImage from '../assets/project-learning.png';

export const projects = [
  { id:'ecommerce-platform', name:'Nova Commerce Platform', category:'Full stack · E-commerce', image:commerceImage, visual:'visual-commerce', stack:['React','Node.js','Express','MongoDB'], description:'A responsive e-commerce experience with product discovery, cart management, secure authentication, order tracking, and an administrator workflow.', challenge:'Keeping cart, inventory, authentication, and order states consistent across the client and server while preserving a fast experience on mobile devices.', improvement:'Add payment gateway integration, product recommendations, seller analytics, automated testing, and real-time inventory notifications.', live:'https://example.com/', github:'https://github.com/' },
  { id:'task-management-app', name:'FlowBoard Workspace', category:'Productivity · SaaS', image:flowboardImage, visual:'visual-tasks', stack:['React','REST API','PostgreSQL','JWT'], description:'A collaborative task-management application with projects, boards, priorities, due dates, progress summaries, and a focused responsive workspace.', challenge:'Designing intuitive interactions while maintaining accessible keyboard behavior and predictable synchronization across multiple views.', improvement:'Introduce real-time collaboration, activity history, calendar integration, file attachments, and configurable team permissions.', live:'https://example.com/', github:'https://github.com/' },
  { id:'learning-platform', name:'SkillSpring Learning Hub', category:'Education · Web app', image:learningImage, visual:'visual-learning', stack:['React','Node.js','Express','MongoDB'], description:'An online learning platform where students explore courses, follow lessons, complete activities, and monitor progress through a focused dashboard.', challenge:'Structuring course and progress data so the learning experience stays simple while supporting flexible content and reliable completion tracking.', improvement:'Add video streaming, instructor tools, certificates, discussions, subscriptions, and personalized course recommendations.', live:'https://example.com/', github:'https://github.com/' },
  { id:'finance-dashboard', name:'FinSight Finance Dashboard', category:'Fintech · Dashboard', image:financeImage, visual:'visual-commerce', stack:['React','TypeScript','Chart.js','REST API'], description:'A personal finance dashboard for understanding balances, spending categories, recent transactions, budgets, and savings goals at a glance.', challenge:'Making dense financial information easy to scan while keeping calculations, filters, and visual summaries consistent across screen sizes.', improvement:'Add bank integrations, recurring-transaction detection, exportable reports, goal notifications, and multi-currency support.', live:'https://example.com/', github:'https://github.com/' }
];
