import React from 'react';
import {createRoot} from 'react-dom/client';
import '../styles.css';
import {projects} from './data';
import {Footer,Header,ProjectVisual,Reveal} from './components';

const skills=[['Frontend',['HTML5','CSS3','JavaScript','React','Responsive UI'],'92%'],['Backend',['Node.js','Express','REST APIs','Authentication','Validation'],'84%'],['Database',['MongoDB','PostgreSQL','Data modeling','Queries','Cloud storage'],'80%'],['Tools & workflow',['Git','GitHub','Vite','Figma','Deployment'],'88%']];

function ContactForm(){const [note,setNote]=React.useState('This opens your default email application.');function submit(e){e.preventDefault();const d=new FormData(e.currentTarget);setNote('Your email application is opening…');location.href=`mailto:ayonpal989@gmail.com?subject=${encodeURIComponent(d.get('subject'))}&body=${encodeURIComponent(`Name: ${d.get('name')}\nEmail: ${d.get('email')}\n\n${d.get('message')}`)}`};return <Reveal as="form" className="contact-form" onSubmit={submit}><label>Name<input name="name" required placeholder="Your name"/></label><label>Email<input type="email" name="email" required placeholder="you@example.com"/></label><label>Subject<input name="subject" required placeholder="How can I help?"/></label><label>Message<textarea name="message" required rows="5" placeholder="Tell me a little about your project..."/></label><button className="button" type="submit">Send message <span>↗</span></button><p className="form-note">{note}</p></Reveal>}

function App(){return <><Header/><main>
<section className="hero" id="home"><div className="hero-glow glow-one"/><div className="hero-glow glow-two"/><div className="container hero-grid"><Reveal className="hero-copy"><p className="eyebrow">Hello, I'm Ayon</p><h1>I build <span>digital products.</span></h1><p className="designation">Full Stack <span>Web Developer</span></p><p className="hero-text">I turn ideas into fast, reliable, and user-friendly web experiences—from polished interfaces to dependable backend systems.</p><div className="hero-actions"><a className="button" href="#contact">Let's talk <span>↗</span></a><a className="button button-ghost" href="#projects">View my projects <span>↓</span></a></div><div className="social-links" aria-label="Social links"><a href="https://github.com/" target="_blank" rel="noreferrer" aria-label="GitHub"><img className="social-icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original.svg" alt=""/></a><a href="https://www.linkedin.com/" target="_blank" rel="noreferrer" aria-label="LinkedIn">in</a><a href="https://twitter.com/" target="_blank" rel="noreferrer" aria-label="Twitter">X</a><a href="https://www.facebook.com/" target="_blank" rel="noreferrer" aria-label="Facebook">f</a><a href="mailto:ayonpal989@gmail.com" aria-label="Email">@</a></div></Reveal><Reveal className="portrait-wrap"><div className="portrait-frame"><img src="./assets/ayon-profile.jpeg" alt="Ayon — Full Stack Web Developer"/></div><div className="floating-card card-role"><span>✦</span><div><small>Current focus</small><strong>Full Stack Development</strong></div></div><div className="floating-card card-location"><span>⌖</span><div><small>Available for</small><strong>Remote opportunities</strong></div></div></Reveal></div></section>
<section className="section section-light" id="about"><div className="container about-grid"><Reveal className="section-heading"><p className="eyebrow">About me</p><h2>Curiosity turned into a career built around <span>data with purpose.</span></h2></Reveal><Reveal className="about-copy"><p>My programming journey began with small HTML and CSS experiments and quickly grew into a passion for building complete web applications. JavaScript showed me how interfaces could feel alive; backend development taught me how thoughtful architecture keeps products reliable as they grow.</p><p>I enjoy turning rough ideas into clean, useful experiences. My favorite work combines responsive UI, reusable components, practical APIs, and careful problem-solving. I care about accessibility, performance, readable code, and the small interaction details that make a product feel finished.</p><p>Outside programming, I enjoy football, photography, music, and exploring new places. Those interests keep me curious and creative—and that same energy shapes how I learn new tools, collaborate with people, and approach difficult technical challenges.</p><div className="about-facts"><div><strong>Clean</strong><span>Readable code</span></div><div><strong>Fast</strong><span>Modern UI</span></div><div><strong>Open</strong><span>Team player</span></div></div></Reveal></div></section>
<section className="section" id="skills"><div className="container"><Reveal className="section-title"><p className="eyebrow">Core capabilities</p><h2>Skills for building <span>complete digital products.</span></h2><p>A modern toolkit covering frontend, backend, databases, and developer workflow.</p></Reveal><div className="skills-grid">{skills.map(([title,tags,level],i)=><Reveal as="article" className="skill-card" key={title}><div className="skill-icon">0{i+1}</div><h3>{title}</h3><div className="skill-tags">{tags.map(tag=><span key={tag}>{tag}</span>)}</div><div className="meter"><i style={{'--level':level}}/></div></Reveal>)}</div></div></section>
<section className="section section-dark" id="education"><div className="container timeline-layout"><Reveal className="section-heading"><p className="eyebrow">Education</p><h2>Academic foundation &amp; continuous learning.</h2><p className="muted">Replace the clearly marked academic placeholders below with Ayon's verified information.</p></Reveal><Reveal className="timeline"><article><span className="timeline-dot"/><p className="timeline-year">Bachelor's degree</p><h3>Degree title — update here</h3><p>University name · Graduation year</p><small>Add the verified major, result, relevant coursework, and academic achievements here.</small></article><article><span className="timeline-dot"/><p className="timeline-year">Web development</p><h3>Full Stack Development</h3><p>Project-based professional learning</p><small>Hands-on learning through responsive websites, React applications, backend APIs, databases, Git, and deployment.</small></article></Reveal></div></section>
<section className="section" id="experience"><div className="container"><Reveal className="section-title"><p className="eyebrow">Experience</p><h2>Where data meets <span>real-world impact.</span></h2></Reveal><Reveal className="experience-card"><div className="experience-date">Current</div><div className="experience-main"><p className="company">Independent &amp; project work</p><h3>Full Stack Developer</h3><p>Building complete, responsive web experiences from initial interface concepts to data-driven functionality and production deployment.</p><ul><li>Develop reusable, accessible frontend components.</li><li>Design APIs, authentication flows, and database structures.</li><li>Test, optimize, document, and deploy modern web applications.</li></ul></div></Reveal></div></section>
<section className="section section-light" id="projects"><div className="container"><Reveal className="section-title split-title"><div><p className="eyebrow">Selected projects</p><h2>Work that turns information into <span>action.</span></h2></div><p>Open each case study for its stack, challenges, links, and future plans.</p></Reveal><div className="projects-grid">{projects.map((p,i)=><Reveal as="article" className="project-card" key={p.id}><ProjectVisual project={p} index={i} linked/><div className="project-content"><p>{p.category}</p><h3>{p.name}</h3><p className="project-summary">{p.description}</p><a className="text-link" href={`project.html?id=${p.id}`}>View details <span>↗</span></a></div></Reveal>)}</div></div></section>
<section className="section contact-section" id="contact"><div className="container contact-grid"><Reveal className="contact-copy"><p className="eyebrow">Contact</p><h2>Have a project in mind? <span>Let's build it.</span></h2><p>I'm open to frontend, backend, full-stack, and collaborative web-development opportunities.</p><div className="contact-list"><a href="mailto:ayonpal989@gmail.com"><span>@</span><div><small>Email</small><strong>ayonpal989@gmail.com</strong></div></a><a href="https://wa.me/8801989492958" target="_blank" rel="noreferrer" aria-label="Chat with Ayon on WhatsApp"><span>◉</span><div><small>WhatsApp</small><strong>01989-492958</strong></div></a><a href="tel:+8801961645231" aria-label="Call Ayon"><span>☎</span><div><small>Phone</small><strong>01961-645231</strong></div></a><div><span>⌖</span><div><small>Availability</small><strong>Remote and on-site</strong></div></div></div></Reveal><ContactForm/></div></section>
</main><Footer/></>}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
